package org.dpc.cxf.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2014-08-20T13:25:19.952+08:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://ws.cxf.dpc.org/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://ws.cxf.dpc.org/HelloWorld/sayHiRequest", output = "http://ws.cxf.dpc.org/HelloWorld/sayHiResponse")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://ws.cxf.dpc.org/", className = "org.dpc.cxf.ws.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://ws.cxf.dpc.org/", className = "org.dpc.cxf.ws.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
